name: CI

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators
      - name: Check formatting
        run: |
          nix fmt
          git diff --exit-code

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators
      - name: Evaluate checks
        run: nix flake check --no-build
